services:
  - type: web
    name: react-app-backend
    env: node
    region: ohio
    build:
      command: |
        npm install
        npm run build
    run: "npm start"
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
    plan: free
    autoDeploy: true
